### ISSUE TITLE
PDG_NodeTypes.so linkage error with custom USD namespace

### ISSUE THREAD

**Issue by nrusch** [sideeffects/HoudiniUsdBridge#12]
`PDG_NodeTypes.so` is linked against the USD libraries, but until somewhat recently, it didn't actually reference any USD symbols. However, at some point, it started making use of USD for something. Since we build USD with a custom namespace, `PDG_NodeTypes.so` now throws an undefined symbol error at startup.

This isn't really causing a problem for us, since we don't use PDG, but I just through it was worth mentioning.

Note: I'm jumping between 18.0.348 and 18.0.372, so I'm not sure exactly which intermediate build introduced the change in behavior.

**Comment by marktucker** [comment]
Thanks, I'll see if we can eliminate this dependency (or if necessary, publish the PDG_NodeTypes code to HoudiniUsdBridge).

**Comment by cgrebeld** [comment]
This should be fixed in 18.0.378

**Comment by nrusch** [comment]
Hey @cgrebeld, this still seems to be happening in 18.0.401 (although it still doesn't seem to cause any issues with Houdini itself).

The error I'm seeing is:

`PDG_NodeTypes.so: undefined symbol: _ZN32pxrInternal_v0_19__pxrReserved__7TfTokenC1EPKc`

The demangled symbol is: `pxrInternal_v0_19__pxrReserved__::TfToken::TfToken(char const*)`

**Comment by cgrebeld** [comment]
Apologies, this should actually be fixed in 18.0.405

**Comment by marktucker** [comment]
Closing this out after two years of inactivity. Hopefully the last update that this was fixed was accurate.
